from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List

from core.models import AttackSurface, Finding
from core.plugin_request import send_plugin_test


@dataclass
class TestCase:
    """One bounded request generated by a scanner plugin."""

    __test__ = False  # prevent pytest from collecting
    plugin: str
    surface_id: str
    param: str
    kind: str  # query/body/path/header/cookie
    payload: str
    method_override: str | None = None
    allow_redirects: bool | None = None
    notes: str | None = None
    baseline_key: str = ""
    input_path: str = ""  # canonical nested insertion path when available


@dataclass
class VerificationResult:
    """Result returned by a plugin verifier for one test case."""

    is_verified: bool
    confidence: str  # LOW/MEDIUM/HIGH
    evidence: Dict[str, Any]
    reproduction: Dict[str, Any]
    severity: str = "MEDIUM"
    verification_status: str = "suspected"
    rationale: str = ""


class BasePlugin(ABC):
    """Common contract for bounded scanner plugins."""

    name: str = "BasePlugin"
    supported_input_kinds: List[str] = ["query", "body", "path", "header", "cookie"]

    def __init__(self, request_manager, config):
        self.session = request_manager
        self.config = config

    @classmethod
    def enabled(cls, config: Dict) -> bool:
        return bool(config.get("enabled", False))

    @classmethod
    def max_tests_per_surface(cls, config: Dict) -> int:
        try:
            return int(config.get("max_tests_per_surface", 6))
        except (TypeError, ValueError):
            return 6

    @abstractmethod
    def applicable(self, surface: AttackSurface) -> bool:
        ...

    @abstractmethod
    def generate_tests(self, surface: AttackSurface, context: Dict) -> List[TestCase]:
        ...

    @abstractmethod
    def verify(
        self,
        testcase: TestCase,
        baseline,
        response,
        context: Dict,
    ) -> VerificationResult:
        ...

    @abstractmethod
    def build_finding(
        self,
        testcase: TestCase,
        vres: VerificationResult,
        surface: AttackSurface,
    ) -> Finding:
        ...

    def run(self, surface: AttackSurface, context: Dict) -> List[Finding]:
        """Compatibility adapter for plugins that still call ``run`` directly."""

        findings: List[Finding] = []
        if all(
            hasattr(self, attr)
            for attr in ("generate_tests", "verify", "build_finding")
        ):
            baseline = context.get("baseline")
            tests = self.generate_tests(surface, context)[
                : self.max_tests_per_surface(getattr(self, "config", {}))
            ]
            for tc in tests:
                try:
                    resp = send_plugin_test(self.session, surface, tc)
                    vres = self.verify(tc, baseline, resp, context)
                    if vres.is_verified:
                        findings.append(self.build_finding(tc, vres, surface))
                except Exception as exc:
                    context.setdefault("errors", []).append(str(exc))
                    continue
        else:
            raise NotImplementedError("Legacy run not implemented for this plugin.")
        return findings
