from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List

from core.models import AttackSurface, Finding


EVIDENCE_SCHEMA_V1 = "webvulnscanner/evidence-v1"
VALID_CONFIDENCE = {"LOW", "MEDIUM", "HIGH"}
VALID_VERIFICATION_STATUS = {"not_reproducible", "informational", "suspected", "detected", "verified"}


@dataclass(frozen=True)
class PluginContract:
    """Runtime guardrails applied to every active plugin on every surface."""

    timeout_seconds: float
    request_budget: int
    max_tests_per_surface: int
    evidence_schema: str = EVIDENCE_SCHEMA_V1


@dataclass
class TestCase:
    """Single bounded injection attempt generated by a plugin."""

    __test__ = False  # prevent pytest from collecting
    plugin: str
    surface_id: str
    param: str
    kind: str  # query/body/path/header/cookie
    payload: str
    method_override: str | None = None
    notes: str | None = None
    baseline_key: str = ""


@dataclass
class VerificationResult:
    """Outcome from plugin.verify for a given test case."""

    is_verified: bool
    confidence: str  # LOW/MEDIUM/HIGH
    evidence: Dict[str, Any]
    reproduction: Dict[str, Any]
    severity: str = "MEDIUM"
    verification_status: str = "suspected"
    rationale: str = ""
    evidence_schema: str = EVIDENCE_SCHEMA_V1


class BasePlugin(ABC):
    """Explicit v2 plugin contract used by the scanner."""

    name: str = "BasePlugin"
    supported_input_kinds: List[str] = ["query", "body", "path", "header", "cookie"]

    def __init__(self, request_manager, config):
        self.session = request_manager
        self.config = config

    @classmethod
    def enabled(cls, config: Dict) -> bool:
        return bool(config.get("enabled", False))

    @classmethod
    def max_tests_per_surface(cls, config: Dict) -> int:
        try:
            return max(1, min(100, int(config.get("max_tests_per_surface", 6))))
        except (TypeError, ValueError):
            return 6

    def contract(self, config: Dict) -> PluginContract:
        max_tests = self.max_tests_per_surface(config)
        try:
            timeout = float(config.get("timeout_seconds", 10.0))
        except (TypeError, ValueError):
            timeout = 10.0
        try:
            request_budget = int(config.get("request_budget", max_tests))
        except (TypeError, ValueError):
            request_budget = max_tests
        return PluginContract(
            timeout_seconds=max(0.25, min(60.0, timeout)),
            request_budget=max(1, min(100, request_budget)),
            max_tests_per_surface=max_tests,
        )

    def validate_testcase(self, testcase: TestCase, surface: AttackSurface) -> None:
        if not isinstance(testcase, TestCase):
            raise ValueError(f"{self.name}: generate_tests returned a non-TestCase value")
        if testcase.plugin != self.name:
            raise ValueError(f"{self.name}: testcase plugin mismatch: {testcase.plugin!r}")
        if testcase.surface_id != surface.id:
            raise ValueError(f"{self.name}: testcase escaped the active surface")
        if testcase.kind not in self.supported_input_kinds:
            raise ValueError(f"{self.name}: unsupported input kind: {testcase.kind!r}")
        if not testcase.param or not isinstance(testcase.param, str):
            raise ValueError(f"{self.name}: testcase parameter must be a non-empty string")
        if not isinstance(testcase.payload, str):
            raise ValueError(f"{self.name}: testcase payload must be a string")

    def validate_verification_result(self, result: VerificationResult) -> None:
        if not isinstance(result, VerificationResult):
            raise ValueError(f"{self.name}: verify returned a non-VerificationResult value")
        if result.confidence not in VALID_CONFIDENCE:
            raise ValueError(f"{self.name}: invalid confidence: {result.confidence!r}")
        if result.verification_status not in VALID_VERIFICATION_STATUS:
            raise ValueError(f"{self.name}: invalid verification_status: {result.verification_status!r}")
        if result.evidence_schema != EVIDENCE_SCHEMA_V1:
            raise ValueError(f"{self.name}: unsupported evidence schema: {result.evidence_schema!r}")
        if not isinstance(result.evidence, dict) or not isinstance(result.reproduction, dict):
            raise ValueError(f"{self.name}: evidence and reproduction must be dictionaries")
        if result.is_verified and not result.evidence:
            raise ValueError(f"{self.name}: reportable results require evidence")
        if result.is_verified and not result.reproduction:
            raise ValueError(f"{self.name}: reportable results require reproduction metadata")

    @abstractmethod
    def applicable(self, surface: AttackSurface) -> bool:
        ...

    @abstractmethod
    def generate_tests(self, surface: AttackSurface, context: Dict) -> List[TestCase]:
        ...

    @abstractmethod
    def verify(self, testcase: TestCase, baseline, response, context: Dict) -> VerificationResult:
        ...

    @abstractmethod
    def build_finding(self, testcase: TestCase, vres: VerificationResult, surface: AttackSurface) -> Finding:
        ...

    def run(self, surface: AttackSurface, context: Dict) -> List[Finding]:
        """Legacy adapter kept for compatibility; all requests remain centralized."""

        findings: List[Finding] = []
        if all(hasattr(self, attr) for attr in ("generate_tests", "verify", "build_finding")):
            baseline = context.get("baseline")
            contract = self.contract(getattr(self, "config", {}))
            tests = self.generate_tests(surface, context)[: contract.max_tests_per_surface]
            requests_used = 0
            for tc in tests:
                if requests_used >= contract.request_budget:
                    context.setdefault("errors", []).append(f"{self.name}: request budget exhausted")
                    break
                try:
                    self.validate_testcase(tc, surface)
                    requests_used += 1
                    resp = self.session.send_surface(surface, tc.param, tc.payload)
                    vres = self.verify(tc, baseline, resp, context)
                    self.validate_verification_result(vres)
                    if vres.is_verified:
                        findings.append(self.build_finding(tc, vres, surface))
                except Exception as exc:
                    context.setdefault("errors", []).append(str(exc))
                    continue
        else:
            raise NotImplementedError("Legacy run not implemented for this plugin.")
        return findings
