from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Any, Dict, List

from core.models import AttackSurface, Finding


VALID_CONFIDENCE = {"LOW", "MEDIUM", "HIGH"}
VALID_VERIFICATION_STATUS = {"not_reproducible", "informational", "suspected", "detected", "verified"}


class PluginContractError(RuntimeError):
    """Raised when a plugin violates the bounded scanner contract."""


@dataclass
class TestCase:
    """Single bounded injection attempt generated by a plugin."""

    __test__ = False  # prevent pytest from collecting
    plugin: str
    surface_id: str
    param: str
    kind: str  # query/body/path/header/cookie
    payload: str
    method_override: str | None = None
    notes: str | None = None
    baseline_key: str = ""


@dataclass
class VerificationResult:
    """Outcome from plugin.verify for a single test case."""

    is_verified: bool
    confidence: str  # LOW/MEDIUM/HIGH
    evidence: Dict[str, Any]
    reproduction: Dict[str, Any]
    severity: str = "MEDIUM"
    verification_status: str = "suspected"
    rationale: str = ""


class BasePlugin(ABC):
    """Explicit v2 plugin contract used by the scanner.

    Every plugin is bounded by a per-surface request budget and a request timeout.
    Scope enforcement is delegated to RequestManager, which is the only supported
    outbound HTTP path. Verification results must be structured data so reporters
    can redact and serialize evidence safely.
    """

    name: str = "BasePlugin"
    supported_input_kinds: List[str] = ["query", "body", "path", "header", "cookie"]

    def __init__(self, request_manager, config):
        self.session = request_manager
        self.config = config

    @classmethod
    def enabled(cls, config: Dict) -> bool:
        return bool(config.get("enabled", False))

    @classmethod
    def max_tests_per_surface(cls, config: Dict) -> int:
        try:
            return max(0, int(config.get("max_tests_per_surface", 6)))
        except (TypeError, ValueError):
            return 6

    def request_budget(self, config: Dict) -> int:
        """Maximum candidate requests this plugin may issue for one surface.

        This deliberately dispatches `max_tests_per_surface` through the instance
        because older plugins override that hook as an instance method.
        """
        default = self.max_tests_per_surface(config)
        try:
            value = int(config.get("request_budget", default))
        except (TypeError, ValueError):
            value = default
        return max(0, min(value, default))

    @classmethod
    def request_timeout_seconds(cls, config: Dict, scanner_timeout: float = 10.0) -> float:
        """Per-request timeout capped by the scanner-wide timeout."""
        try:
            scanner_value = max(0.1, float(scanner_timeout))
        except (TypeError, ValueError):
            scanner_value = 10.0
        try:
            requested = float(config.get("timeout_seconds", scanner_value))
        except (TypeError, ValueError):
            requested = scanner_value
        return max(0.1, min(requested, scanner_value))

    @classmethod
    def evidence_contract(cls) -> Dict[str, str]:
        return {
            "evidence": "dict; non-empty for reportable results",
            "reproduction": "dict; bounded reproduction metadata, never executable automation",
            "confidence": "LOW|MEDIUM|HIGH",
            "verification_status": "not_reproducible|informational|suspected|detected|verified",
        }

    def validate_testcase(self, testcase: TestCase, surface: AttackSurface) -> None:
        if not isinstance(testcase, TestCase):
            raise PluginContractError(f"{self.name}: generate_tests returned a non-TestCase value")
        if testcase.plugin != self.name:
            raise PluginContractError(f"{self.name}: testcase plugin field does not match plugin name")
        if testcase.surface_id != surface.id:
            raise PluginContractError(f"{self.name}: testcase escaped its originating surface")
        if testcase.kind not in self.supported_input_kinds:
            raise PluginContractError(f"{self.name}: unsupported input kind {testcase.kind!r}")
        if not isinstance(testcase.payload, str):
            raise PluginContractError(f"{self.name}: payload must be a string")

    def validate_verification_result(self, result: VerificationResult) -> None:
        if not isinstance(result, VerificationResult):
            raise PluginContractError(f"{self.name}: verify returned a non-VerificationResult value")
        if str(result.confidence).upper() not in VALID_CONFIDENCE:
            raise PluginContractError(f"{self.name}: invalid confidence {result.confidence!r}")
        if str(result.verification_status).lower() not in VALID_VERIFICATION_STATUS:
            raise PluginContractError(f"{self.name}: invalid verification status {result.verification_status!r}")
        if not isinstance(result.evidence, dict) or not isinstance(result.reproduction, dict):
            raise PluginContractError(f"{self.name}: evidence and reproduction must be dictionaries")
        if result.is_verified and not result.evidence:
            raise PluginContractError(f"{self.name}: reportable verification result has no evidence")
        if result.is_verified and not result.reproduction:
            raise PluginContractError(f"{self.name}: reportable verification result has no reproduction metadata")

    @abstractmethod
    def applicable(self, surface: AttackSurface) -> bool:
        ...

    @abstractmethod
    def generate_tests(self, surface: AttackSurface, context: Dict) -> List[TestCase]:
        ...

    @abstractmethod
    def verify(self, testcase: TestCase, baseline, response, context: Dict) -> VerificationResult:
        ...

    @abstractmethod
    def build_finding(self, testcase: TestCase, vres: VerificationResult, surface: AttackSurface) -> Finding:
        ...

    def run(self, surface: AttackSurface, context: Dict) -> List[Finding]:
        """Legacy adapter that still enforces the v2 budget and result contract."""
        findings: List[Finding] = []
        if all(hasattr(self, attr) for attr in ("generate_tests", "verify", "build_finding")):
            baseline = context.get("baseline")
            budget = self.request_budget(getattr(self, "config", {}))
            tests = self.generate_tests(surface, context)[:budget]
            for tc in tests:
                try:
                    self.validate_testcase(tc, surface)
                    resp = self.session.send_surface(surface, tc.param, tc.payload)
                    vres = self.verify(tc, baseline, resp, context)
                    self.validate_verification_result(vres)
                    if vres.is_verified:
                        findings.append(self.build_finding(tc, vres, surface))
                except PluginContractError:
                    raise
                except Exception as exc:
                    context.setdefault("errors", []).append(str(exc))
                    continue
        else:
            raise NotImplementedError("Legacy run not implemented for this plugin.")
        return findings
